# Generated by Django 3.2.6 on 2021-08-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='typeingredient',
            options={'ordering': ('name',), 'verbose_name': 'TypeIngredient', 'verbose_name_plural': 'TypeIngredients'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='idIngredient',
        ),
        migrations.AddField(
            model_name='pizza',
            name='idIngredient',
            field=models.ManyToManyField(related_name='Ingredient', to='pizzaMaker.Ingredient'),
        ),
    ]
